# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prayer',
            new_name='Request',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='prayer_text',
            new_name='request_text',
        ),
    ]
